name: angular_analyzer_plugin
version: 2.0.0
description: Dart analyzer plugin for Angular
homepage: https://angulardart.xyz/
repository: https://github.com/angulardart-community/nganalyzer
environment:
  sdk: ">=2.5.0-dev.1.0 <3.0.0"

dependencies:
  analyzer: ^0.37.0
  analyzer_plugin: ^0.1.0
  angular_ast: '0.5.11'
  crypto: '>=1.1.1 <3.0.0'
  meta: ^1.1.4
  plugin: ^0.2.0
  yaml: ^2.1.2

dev_dependencies:
  lint: ^1.7.2
  mockito: ^3.0.0
  test: ^1.2.0
  test_reflective_loader: ^0.1.0

# === vvv REMOVE WHEN PUBLISHING vvv ===
# dependency_overrides:
#   angular_ast:
#       path: ../angular_ast
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
